### ISSUE TITLE
Credential updates - who is allowed to update a credential

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/domain-models#10]
The system needs to allow only authorized users to update or create a new version of a credential. This would suggest only the original creator - which would be a limitation. 
Should another user from the same organization be able to update the credential?
What is the process to add a person to an organization?  
Or, more generally, how will a person assign permission for others to update a credential?

**Comment by CTITechPlanning** [comment]
Currently system will only allow updated by person who is a member of the managing org.
