### ISSUE TITLE
Publishing learning opportunities and assessments to the credential registry

### ISSUE THREAD

**Issue by mparsons1953** [CredentialTransparencyInitiative/domain-models#15]
@stuartasutton 
We have discussed whether or not a learning opportunity or an assessment should be published to the registry. 
Minimal data is published for the latter when published with a condition profile, typically the name and url. All the competency data is (typically) associated with a learning opportunity or assessment.  
In general, it seems important that assessment and learning opportunity information be published to the registry, and even more so, that the competencies be published.

**Comment by stuartasutton** [comment]
@mparsons1953, @jkitchensSIUC & @CTITechPlanning,  we probably better get our terms clear. Currently, CTDL has classes for both LearningOpportunity and Assessment (in addiiton to LearningOpportunityProfile and AssessmentProfile. The emerging schema.org/Course & schema.org/CourseInstance are kinds of LearningOpportunity. So, my undersanding is that any descriptions of resources of the classes Course and CourseInstance will rely on the schema.org properties nearing approval. There is no RDF-like set of properties describing things of the Assessment class that I am aware of (i.e., there are xml-like frameworks in IMS for assessments)...are there others formally declared? And, beyond formal courses, what are the other subclasses of a LearningOpportunity super-class? So, that seems the state of being able to create resource description for these classes. 

**Then*** there is the question you raise--does CTI intend to host descriptions stemming from those classes: (1) host Course descriptions; (2) host CourseInstance descriptions; and (3) host Assessment descriptions. From the intro to Phil at the last TAC call:

<img width="1341" alt="screenshot 2016-09-09 10 20 32" src="https://cloud.githubusercontent.com/assets/2939046/18396202/30f29184-7677-11e6-9eb1-3f6f4606cf13.png">

**Comment by mparsons1953** [comment]
We have decided to publish the AssessmentProfile and LearningOpportunity profiles to the registry
