### ISSUE TITLE
Can a credential have more than one credentialing body

### ISSUE THREAD

**Issue by siuccwd** [CredentialTransparencyInitiative/domain-models#5]
Michael Parsons:
Is it possible to have more than one credentialing body associated with a credential?

**Comment by stuartasutton** [comment]
@suiccwd, if by credentialing body you mean a [credential issuer](http://www.credreg.net/page/glossary#credentialIssuer), there is nothing on the CTI domain model that says a credential could not have more than one credential issuer. 

Of course, a specific application using the CTI description language could constrain the number of issuers.
